name: MLOps Integración Continua (CI) / Despliegue Continuo (CD)

# -- cuando se va a ejecutar este workflow 
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

# -- los trabajos que se van a ejecutar
jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      # 1. Descarga el código de tu repositorio
      - name: Descargar el código
        uses: actions/checkout@v3

      # 2. Revisa que el código Python esté bien
      - name: Configurar Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      # 3. La prueba de fuego: Intenta construir tu Dockerfile
      - name: Construir Imagen de Docker
        run: |
          docker build -t agrosmart-api:latest .
          echo "El contenedor Docker se construyó exitosamente"

  deploy:
    name: Despliegue en Google Cloud Run
    needs: build-and-test # Solo se ejecuta si el trabajo de build-and-test es exitoso
    if: github.event_name == 'push' && github.ref == 'refs/heads/main' # Solo despliega en la rama main
    runs-on: ubuntu-latest

    steps:

      - name: Checkout code
        uses: actions/checkout@v3

      - id: 'auth'
        uses: 'google-github-actions/auth@v1'
        with:
          credentials_json: '${{ secrets.GCP_SA_KEY }}'

      - name: Configurar Docker para GCP
        run: gcloud auth configure-docker us-central1-docker.pkg.dev


      - name: Construir y subir imagen a Artifact Registry
        run: |
          docker build -t us-central1-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/agrosmart/api:${{ github.sha }} .
          docker push us-central1-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/agrosmart/api:${{ github.sha }}

      - name: Despliegue en Cloud Run
        uses: google-github-actions/deploy-cloudrun@v1
        with:
          service: agrosmart-api # <-- ¡Aquí está el cambio clave!
          image: us-central1-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/agrosmart/api:${{ github.sha }}
          region: us-central1
          flags: '--allow-unauthenticated'

